name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install pyinstaller
      run: pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --icon=logo.ico --add-data "logo.ico;." QphotoRenamer.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: dist/QphotoRenamer.exe